#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# topggpy documentation build configuration file, created by
# sphinx-quickstart on Thu Feb  8 18:32:44 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import os
import sys

sys.path.insert(0, os.path.abspath("../"))

from topgg import __version__ as version

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.extlinks",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx_reredirects",
]

autodoc_member_order = "groupwise"

extlinks = {
    "issue": ("https://github.com/top-gg-community/python-sdk/issues/%s", "#%s"),
}

intersphinx_mapping = {
    "py": ("https://docs.python.org/3", None),
    "discord": ("https://discordpy.readthedocs.io/en/latest/", None),
    "aiohttp": ("https://docs.aiohttp.org/en/stable/", None),
}

redirects = {
    "repository": "https://github.com/top-gg-community/python-sdk",
    "support": "https://discord.gg/dbl",
    "api/index": "autopost.html",
    "examples/index": "discord_py.html",
    "examples/discord_py": "https://github.com/Top-gg-Community/python-sdk/tree/master/examples/discordpy_example",
    "examples/hikari": "https://github.com/Top-gg-Community/python-sdk/tree/master/examples/hikari_example",
}

releases_github_path = "top-gg-community/python-sdk"
source_suffix = ".rst"
master_doc = "index"

project = "topggpy"
copyright = "2021 Assanali Mukhanov; 2024 null8626"
author = "null8626"
release = version

language = "en"
exclude_patterns = ["_build"]

html_js_files = ["script.js"]
html_css_files = [
    "style.css",
    "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Roboto+Mono&display=swap",
]
html_favicon = "_static/favicon.ico"
html_theme = "furo"
html_logo = "topgg.svg"
html_static_path = ["_static"]
html_show_sphinx = False
html_show_copyright = True
htmlhelp_basename = "topggpydoc"

latex_documents = [
    (master_doc, "topggpy.tex", "topggpy Documentation", "Assanali Mukhanov", "manual"),
]

man_pages = [(master_doc, "topggpy", "topggpy Documentation", [author], 1)]

texinfo_documents = [
    (
        master_doc,
        "topggpy",
        "topggpy Documentation",
        author,
        "topggpy",
        "One line description of project.",
        "Miscellaneous",
    ),
]
